name: Setup Basic Store Structure

on:
  push:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Basic Structure
        run: |
          # Create main directories
          mkdir -p css js images admin

          # Create index.html
          cat > index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>RedQuests Store</title>
              <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
              <link href="css/style.css" rel="stylesheet">
          </head>
          <body>
              <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                  <div class="container">
                      <a class="navbar-brand" href="#">RedQuests</a>
                      <div class="navbar-nav">
                          <a class="nav-link" href="admin/index.html">Admin</a>
                      </div>
                  </div>
              </nav>

              <div class="container mt-4">
                  <div id="products" class="row">
                      <!-- Products will load here -->
                  </div>
              </div>

              <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
              <script src="js/main.js"></script>
          </body>
          </html>
          EOL

          # Create admin page
          cat > admin/index.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Admin - RedQuests</title>
              <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
              <link href="../css/admin.css" rel="stylesheet">
          </head>
          <body>
              <div class="container mt-4">
                  <h1>Admin Panel</h1>
                  <div class="row mt-4">
                      <div class="col-md-12">
                          <button class="btn btn-primary" onclick="addProduct()">Add Product</button>
                          <div id="productList" class="mt-4">
                              <!-- Products will load here -->
                          </div>
                      </div>
                  </div>
              </div>

              <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
              <script src="../js/admin.js"></script>
          </body>
          </html>
          EOL

          # Create basic CSS
          cat > css/style.css << 'EOL'
          .product-card {
              margin-bottom: 20px;
              transition: transform 0.3s;
          }
          .product-card:hover {
              transform: translateY(-5px);
          }
          EOL

          # Create admin CSS
          cat > css/admin.css << 'EOL'
          .product-item {
              padding: 10px;
              border-bottom: 1px solid #eee;
          }
          EOL

          # Create main JavaScript
          cat > js/main.js << 'EOL'
          // Load and display products
          function loadProducts() {
              const products = JSON.parse(localStorage.getItem('products')) || [];
              const container = document.getElementById('products');
              
              container.innerHTML = products.map(product => `
                  <div class="col-md-4">
                      <div class="card product-card">
                          <div class="card-body">
                              <h5 class="card-title">${product.name}</h5>
                              <p class="card-text">$${product.price}</p>
                              <button class="btn btn-primary">Add to Cart</button>
                          </div>
                      </div>
                  </div>
              `).join('');
          }

          document.addEventListener('DOMContentLoaded', loadProducts);
          EOL

          # Create admin JavaScript
          cat > js/admin.js << 'EOL'
          function addProduct() {
              const name = prompt('Enter product name:');
              const price = prompt('Enter product price:');
              
              if (name && price) {
                  const products = JSON.parse(localStorage.getItem('products')) || [];
                  products.push({ name, price });
                  localStorage.setItem('products', JSON.stringify(products));
                  loadProductList();
              }
          }

          function loadProductList() {
              const products = JSON.parse(localStorage.getItem('products')) || [];
              const container = document.getElementById('productList');
              
              container.innerHTML = products.map(product => `
                  <div class="product-item">
                      <h5>${product.name}</h5>
                      <p>$${product.price}</p>
                  </div>
              `).join('');
          }

          document.addEventListener('DOMContentLoaded', loadProductList);
          EOL

          # Create README
          cat > README.md << 'EOL'
          # RedQuests Store

          A simple e-commerce platform using HTML, CSS, and JavaScript.

          ## Features
          - Product listing
          - Basic admin panel
          - Local storage for product data

          ## Setup
          1. Clone the repository
          2. Open index.html in your browser
          3. Access admin panel at admin/index.html
          EOL

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
